pipeline:
  name: testnew
  identifier: testnew
  projectIdentifier: my_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.githubplaywrightrepo
        build: <+input>
  stages:
    - stage:
        name: code
        identifier: code
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: VM
            spec:
              type: Pool
              spec:
                poolName: test
                os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      pwd
                                            ls -la
                                            node --version
                                            npm --version
                                            npm ci
                                            npx playwright test
